import Barchart from '@/components/Barchart'
import Header from '@/components/Header'
import Recentorders from '@/components/Recentorders'
import Topcards from '@/components/Topcards'
import { Inter } from 'next/font/google'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-gray-100 min-h-screen">
        
        <Header/>
        <Topcards/>
        

        <div className=' grid md:grid-cols-3  gap-2 pt-4 '>
          <div className=' md:col-span-2'>
          <Barchart/>
          </div>
          <div className=' w-full md:col-span-1'>
          <Recentorders/>
          </div>
          
        </div>
        
      </main>
    </>
  )
}
